version: "3.5"

networks:
  chicken:

services:
  e-chicken-ui:
    container_name: "e-chicken-ui"
    build:
      context: .
    privileged: true
    ports:
      - 5000:5000
    networks:
      - chicken
